entrypoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: ":443"

certificatesResolvers:
  myresolver:
    acme:
      email: nesaenz69@gmail.com
      storage: /acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: web

providers:
  docker: {}

log:
  filePath: "/traefik.log"
  level: ERROR
  format: json
